name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload files to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        server-dir: /public_html/ 
        local-dir: ./       
